<?php
require_once __DIR__ . '/../../../config.php';
require_once __DIR__ . '/../../../tcpdf/tcpdf.php';

try {
    // Fetch data from the database
    $stmt = config::getConnexion()->prepare("SELECT * FROM candidature ORDER BY date DESC");
    $stmt->execute();
    $jobs = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (Exception $e) {
    die("Error: " . $e->getMessage());
}

// Create a new PDF document
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Application');
//$pdf->SetTitle('List of Applications');
//$pdf->SetHeaderData('', 0, 'List of Applications', 'Generated by Your Application');

// Set margins
$pdf->SetMargins(10, 10, 10);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 10);

// Add content
$html = '<h2>List of Applications</h2>';
$html .= '<table border="1" cellpadding="5">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>';

foreach ($jobs as $job) {
    $html .= '<tr>
                <td>' . htmlspecialchars($job['ID']) . '</td>
                <td>' . htmlspecialchars($job['nom_candidat']) . '</td>
                <td>' . htmlspecialchars($job['prenom_candidat']) . '</td>
                <td>' . htmlspecialchars($job['email']) . '</td>
                <td>' . htmlspecialchars($job['role']) . '</td>
                <td>' . htmlspecialchars($job['adresse']) . '</td>
                <td>' . htmlspecialchars($job['city']) . '</td>
                <td>' . htmlspecialchars($job['Date']) . '</td>
              </tr>';
}

$html .= '</tbody></table>';

// Write the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF
$pdf->Output('list_of_applications.pdf', 'D');